default: &default
  adapter: postgresql
  encoding: unicode
  username: postgres
  password: password
  host: db
  port: 5432
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: file_covert_website_development

test:
  <<: *default
  database: file_covert_website_test

production:
  <<: *default
  database: file_covert_website_production
